### ISSUE TITLE
Write project introduction in Readme

### ISSUE THREAD

**Issue by jhohlfeld** [jhohlfeld/waterguardian#3]
Let's make sure we have a great readme for this project!

Things worth mentioning (from top of my head):

* about NextJS
* how to operate the dev server
* how to get updates rolled out
* about maptiler

How to install

* install bun (https://bun.sh/docs/installation)
* clone repo
* bun install
* .env einrichten
* bun dev

**Comment by FelipeLohan** [comment]
will help you with your project!

**Comment by jhohlfeld** [comment]
Hey @FelipeLohan, that's very nice! We didn't plan to take on other contributions at this moment tbh.
